#+title: go-aws-sam-sample
#+author: conao3

[[https://github.com/conao3/go-aws-sam-sample][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/go-aws-sam-sample.png]]

[[https://github.com/conao3/go-aws-sam-sample/blob/master/LICENSE][https://img.shields.io/github/license/conao3/go-aws-sam-sample.svg?style=flat-square]]
[[https://github.com/conao3/go-aws-sam-sample/releases][https://img.shields.io/github/tag/conao3/go-aws-sam-sample.svg?style=flat-square]]

A sample project demonstrating how to build and deploy serverless applications on AWS using the Serverless Application Model (SAM) with Go.

* Overview

This repository provides a minimal, working example of an AWS Lambda function written in Go, deployed via AWS SAM. The sample function exposes an HTTP endpoint that returns a greeting along with the caller's IP address.

* Features

- Go-based Lambda function with API Gateway integration
- AWS SAM template for infrastructure as code
- Simple deployment workflow using SAM CLI
- Includes unit tests for the Lambda handler

* Prerequisites

Before getting started, ensure you have the following installed:

- [[https://golang.org/][Go]] (1.15 or later)
- [[https://docs.docker.com/get-docker/][Docker]]
- [[https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html][AWS CLI]]
- [[https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html][AWS SAM CLI]]
- An AWS account with appropriate permissions

* Getting Started

** Installation

Clone the repository:

#+begin_src sh
git clone https://github.com/conao3/go-aws-sam-sample.git
cd go-aws-sam-sample
#+end_src

** Building the Application

Use SAM CLI to build the Lambda function:

#+begin_src sh
sam build
#+end_src

** Deploying to AWS

For the initial deployment, run the guided deploy to configure your stack:

#+begin_src sh
sam build && sam deploy --guided
#+end_src

For subsequent deployments, you can simply run:

#+begin_src sh
sam build && sam deploy
#+end_src

** Testing the API

Once deployed, you can test the endpoint using curl:

#+begin_src sh
curl https://<your-api-id>.execute-api.<region>.amazonaws.com/Prod/hello/
#+end_src

The API Gateway endpoint URL will be displayed in the deployment output.

* Project Structure

#+begin_example
.
├── app/
│   └── hello-world/      # Lambda function source code
│       ├── main.go       # Handler implementation
│       ├── main_test.go  # Unit tests
│       ├── go.mod
│       └── go.sum
├── template.yaml         # SAM template
├── Makefile
└── README.org
#+end_example

* Contributing

Contributions are welcome. Feel free to open an issue or submit a pull request if you have suggestions for improvements.

* License

This project is licensed under the MIT License. See the [[https://github.com/conao3/go-aws-sam-sample/blob/master/LICENSE][LICENSE]] file for details.

* Author

- Naoya Yamashita ([[https://github.com/conao3][conao3]])
